# Generated by Django 3.0.11 on 2020-12-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='constant',
            name='metric',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actions.Metric'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='constant',
            unique_together={('action', 'metric', 'version', 'identifier')},
        ),
    ]
