# Generated by Django 3.0.11 on 2020-12-15 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_formula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constant',
        ),
    ]
