# Generated by Django 3.0.11 on 2020-12-15 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0009_delete_constant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='actions.Question'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='pledge',
            unique_together={('user', 'question')},
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='action',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='attribute',
        ),
    ]
