# Generated by Django 3.0.11 on 2020-12-16 09:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0010_auto_20201215_2057'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pledge',
            new_name='Answer',
        ),
    ]
