# Generated by Django 3.0.11 on 2020-12-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0012_auto_20201216_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='actions.Pledge'),
        ),
    ]
